//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace travel_expenses.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expens
    {
        public int ExpensesId { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public string Address { get; set; }
        public string CompanyName { get; set; }
        public string AdvancePayment { get; set; }
        public string Puspose { get; set; }
    }
}
