//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace travel_expenses.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class travelMngSystemEntities : DbContext
    {
        public travelMngSystemEntities()
            : base("name=travelMngSystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<BusExpens> BusExpenses { get; set; }
        public virtual DbSet<Expens> Expenses { get; set; }
        public virtual DbSet<flightExpens> flightExpenses { get; set; }
        public virtual DbSet<OtherExpens> OtherExpenses { get; set; }
        public virtual DbSet<TrainExpens> TrainExpenses { get; set; }
        public virtual DbSet<Login> Logins { get; set; }
    }
}
