//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace travel_expenses.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OtherExpens
    {
        public int Id { get; set; }
        public string TripId { get; set; }
        public string DeparturePlace { get; set; }
        public string ArrivalPlace { get; set; }
        public string Type { get; set; }
        public string Time { get; set; }
        public string Amount { get; set; }
    }
}
